"""Compatibility re-exports for shared OVIS IDs."""

from ovis_ids import (
    ApprovalId,
    BranchId,
    BridgeActionId,
    CompactionId,
    CorrelationId,
    EventId,
    ExecuteJobId,
    PlanJobId,
    SignalId,
    WorkObjectId,
    generate_approval_id,
    generate_branch_id,
    generate_compaction_id,
    generate_correlation_id,
    generate_event_id,
    generate_execute_job_id,
    generate_plan_job_id,
    generate_prefixed_id,
    generate_signal_id,
    generate_work_object_id,
)

__all__ = [
    "ApprovalId",
    "BranchId",
    "BridgeActionId",
    "CompactionId",
    "CorrelationId",
    "EventId",
    "ExecuteJobId",
    "PlanJobId",
    "SignalId",
    "WorkObjectId",
    "generate_approval_id",
    "generate_branch_id",
    "generate_compaction_id",
    "generate_correlation_id",
    "generate_event_id",
    "generate_execute_job_id",
    "generate_plan_job_id",
    "generate_prefixed_id",
    "generate_signal_id",
    "generate_work_object_id",
]
